export type ShikshaStatus = "Coming Soon" | "Pilot" | "Active";

export type IndiaStateStat = {
  code: string;
  name: string;
  dropoutRate: number; // %
  govtSchools: number; // count
  literacyRate: number; // %
  status: ShikshaStatus;
  projectedDropoutRate: number; // %
};

// Lightweight demo dataset (state-level). In production, replace with UDISE+/NSSO-backed figures.
export const indiaStateStats: IndiaStateStat[] = [
  {
    code: "IN-KA",
    name: "Karnataka",
    dropoutRate: 5.1,
    govtSchools: 43000,
    literacyRate: 75.4,
    status: "Pilot",
    projectedDropoutRate: 3.2,
  },
  {
    code: "IN-TN",
    name: "Tamil Nadu",
    dropoutRate: 3.8,
    govtSchools: 37000,
    literacyRate: 80.1,
    status: "Coming Soon",
    projectedDropoutRate: 2.4,
  },
  {
    code: "IN-TS",
    name: "Telangana",
    dropoutRate: 4.3,
    govtSchools: 25000,
    literacyRate: 72.8,
    status: "Coming Soon",
    projectedDropoutRate: 2.8,
  },
  {
    code: "IN-AP",
    name: "Andhra Pradesh",
    dropoutRate: 5.9,
    govtSchools: 44000,
    literacyRate: 67.4,
    status: "Coming Soon",
    projectedDropoutRate: 3.6,
  },
  {
    code: "IN-KL",
    name: "Kerala",
    dropoutRate: 1.9,
    govtSchools: 9000,
    literacyRate: 94.0,
    status: "Active",
    projectedDropoutRate: 1.2,
  },
  {
    code: "IN-MH",
    name: "Maharashtra",
    dropoutRate: 6.2,
    govtSchools: 62000,
    literacyRate: 82.3,
    status: "Coming Soon",
    projectedDropoutRate: 3.8,
  },
  {
    code: "IN-GJ",
    name: "Gujarat",
    dropoutRate: 6.8,
    govtSchools: 34000,
    literacyRate: 78.0,
    status: "Coming Soon",
    projectedDropoutRate: 4.1,
  },
  {
    code: "IN-RJ",
    name: "Rajasthan",
    dropoutRate: 9.6,
    govtSchools: 67000,
    literacyRate: 66.1,
    status: "Coming Soon",
    projectedDropoutRate: 6.0,
  },
  {
    code: "IN-UP",
    name: "Uttar Pradesh",
    dropoutRate: 10.8,
    govtSchools: 160000,
    literacyRate: 67.7,
    status: "Coming Soon",
    projectedDropoutRate: 6.7,
  },
  {
    code: "IN-BR",
    name: "Bihar",
    dropoutRate: 12.4,
    govtSchools: 74000,
    literacyRate: 63.8,
    status: "Coming Soon",
    projectedDropoutRate: 7.8,
  },
  {
    code: "IN-MP",
    name: "Madhya Pradesh",
    dropoutRate: 9.9,
    govtSchools: 105000,
    literacyRate: 69.3,
    status: "Coming Soon",
    projectedDropoutRate: 6.2,
  },
  {
    code: "IN-JH",
    name: "Jharkhand",
    dropoutRate: 11.1,
    govtSchools: 45000,
    literacyRate: 66.4,
    status: "Coming Soon",
    projectedDropoutRate: 7.0,
  },
  {
    code: "IN-WB",
    name: "West Bengal",
    dropoutRate: 7.4,
    govtSchools: 58000,
    literacyRate: 76.3,
    status: "Coming Soon",
    projectedDropoutRate: 4.6,
  },
  {
    code: "IN-OD",
    name: "Odisha",
    dropoutRate: 8.7,
    govtSchools: 52000,
    literacyRate: 72.9,
    status: "Coming Soon",
    projectedDropoutRate: 5.5,
  },
  {
    code: "IN-AS",
    name: "Assam",
    dropoutRate: 9.1,
    govtSchools: 44000,
    literacyRate: 72.2,
    status: "Coming Soon",
    projectedDropoutRate: 5.8,
  },
  {
    code: "IN-PB",
    name: "Punjab",
    dropoutRate: 4.9,
    govtSchools: 20000,
    literacyRate: 75.8,
    status: "Coming Soon",
    projectedDropoutRate: 3.1,
  },
  {
    code: "IN-HR",
    name: "Haryana",
    dropoutRate: 5.6,
    govtSchools: 15000,
    literacyRate: 75.6,
    status: "Coming Soon",
    projectedDropoutRate: 3.5,
  },
  {
    code: "IN-DL",
    name: "Delhi",
    dropoutRate: 2.6,
    govtSchools: 1100,
    literacyRate: 86.2,
    status: "Pilot",
    projectedDropoutRate: 1.6,
  },
  {
    code: "IN-JK",
    name: "Jammu & Kashmir",
    dropoutRate: 7.9,
    govtSchools: 24000,
    literacyRate: 68.7,
    status: "Coming Soon",
    projectedDropoutRate: 5.0,
  },
  {
    code: "IN-HP",
    name: "Himachal Pradesh",
    dropoutRate: 3.2,
    govtSchools: 14000,
    literacyRate: 83.8,
    status: "Coming Soon",
    projectedDropoutRate: 2.1,
  },
  {
    code: "IN-UK",
    name: "Uttarakhand",
    dropoutRate: 4.1,
    govtSchools: 16000,
    literacyRate: 78.8,
    status: "Coming Soon",
    projectedDropoutRate: 2.6,
  },
  {
    code: "IN-GA",
    name: "Goa",
    dropoutRate: 2.2,
    govtSchools: 900,
    literacyRate: 88.7,
    status: "Coming Soon",
    projectedDropoutRate: 1.4,
  },
  {
    code: "IN-CH",
    name: "Chandigarh",
    dropoutRate: 1.8,
    govtSchools: 120,
    literacyRate: 86.0,
    status: "Coming Soon",
    projectedDropoutRate: 1.1,
  },
  {
    code: "IN-CT",
    name: "Chhattisgarh",
    dropoutRate: 10.3,
    govtSchools: 52000,
    literacyRate: 70.3,
    status: "Coming Soon",
    projectedDropoutRate: 6.4,
  },
  {
    code: "IN-KG",
    name: "Chhattisgarh (Alt Code)",
    dropoutRate: 10.3,
    govtSchools: 52000,
    literacyRate: 70.3,
    status: "Coming Soon",
    projectedDropoutRate: 6.4,
  },
  {
    code: "IN-TR",
    name: "Tripura",
    dropoutRate: 6.0,
    govtSchools: 4500,
    literacyRate: 87.2,
    status: "Coming Soon",
    projectedDropoutRate: 3.7,
  },
  {
    code: "IN-ML",
    name: "Meghalaya",
    dropoutRate: 12.1,
    govtSchools: 9000,
    literacyRate: 75.5,
    status: "Coming Soon",
    projectedDropoutRate: 7.6,
  },
  {
    code: "IN-MN",
    name: "Manipur",
    dropoutRate: 7.1,
    govtSchools: 4300,
    literacyRate: 79.2,
    status: "Coming Soon",
    projectedDropoutRate: 4.4,
  },
  {
    code: "IN-NL",
    name: "Nagaland",
    dropoutRate: 8.4,
    govtSchools: 3200,
    literacyRate: 80.1,
    status: "Coming Soon",
    projectedDropoutRate: 5.2,
  },
  {
    code: "IN-AR",
    name: "Arunachal Pradesh",
    dropoutRate: 13.2,
    govtSchools: 6500,
    literacyRate: 66.9,
    status: "Coming Soon",
    projectedDropoutRate: 8.3,
  },
  {
    code: "IN-MZ",
    name: "Mizoram",
    dropoutRate: 4.0,
    govtSchools: 2600,
    literacyRate: 91.3,
    status: "Coming Soon",
    projectedDropoutRate: 2.5,
  },
  {
    code: "IN-SK",
    name: "Sikkim",
    dropoutRate: 3.6,
    govtSchools: 800,
    literacyRate: 82.2,
    status: "Coming Soon",
    projectedDropoutRate: 2.2,
  },
  {
    code: "IN-BG",
    name: "Bengal (Alt Code)",
    dropoutRate: 7.4,
    govtSchools: 58000,
    literacyRate: 76.3,
    status: "Coming Soon",
    projectedDropoutRate: 4.6,
  },
  {
    code: "IN-PY",
    name: "Puducherry",
    dropoutRate: 2.5,
    govtSchools: 350,
    literacyRate: 86.6,
    status: "Coming Soon",
    projectedDropoutRate: 1.6,
  },
  {
    code: "IN-OR",
    name: "Odisha (Alt Code)",
    dropoutRate: 8.7,
    govtSchools: 52000,
    literacyRate: 72.9,
    status: "Coming Soon",
    projectedDropoutRate: 5.5,
  },
  {
    code: "IN-UT",
    name: "Uttarakhand (Alt Code)",
    dropoutRate: 4.1,
    govtSchools: 16000,
    literacyRate: 78.8,
    status: "Coming Soon",
    projectedDropoutRate: 2.6,
  },
  {
    code: "IN-LA",
    name: "Ladakh",
    dropoutRate: 6.7,
    govtSchools: 1200,
    literacyRate: 77.0,
    status: "Coming Soon",
    projectedDropoutRate: 4.1,
  },
  {
    code: "IN-AN",
    name: "Andaman & Nicobar Islands",
    dropoutRate: 3.4,
    govtSchools: 420,
    literacyRate: 86.6,
    status: "Coming Soon",
    projectedDropoutRate: 2.1,
  },
  {
    code: "IN-LD",
    name: "Lakshadweep",
    dropoutRate: 2.9,
    govtSchools: 45,
    literacyRate: 91.9,
    status: "Coming Soon",
    projectedDropoutRate: 1.8,
  },
  {
    code: "IN-DN",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    dropoutRate: 6.5,
    govtSchools: 520,
    literacyRate: 77.1,
    status: "Coming Soon",
    projectedDropoutRate: 4.0,
  },
];

export const INDIA_METRICS = {
  totalGovtSchools: 1_100_000,
  studentsEnrolled: 250_000_000,
  annualDropouts: 30_000_000,
  statesBelow60Literacy: 8,
} as const;

export function getStateStatByName(name: string) {
  const n = name.toLowerCase().replace(/&/g, "and").replace(/\s+/g, " ").trim();
  return indiaStateStats.find((s) =>
    s.name.toLowerCase().replace(/&/g, "and").includes(n),
  );
}

